server:
  port: 80
spring:
  application:
    name: gateway
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 100
      validation-query: "select 1"
    url: r2dbc:postgresql://localhost:5432/gptalk_db
    username: postgres
    password: root
  cloud:
    gateway:
      routes:
        - id: llm_connector_router
          uri: http://localhost:8080
          predicates:
            Path=/v1/chat/**
      loadbalancer:
        use404: false
#          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@modelKeyResolver}"
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
gptalk:
  gateway:
    auth:
      base-url: http://localhost:9001/api/v1
